//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos()
        {
            this.AsignacionCuestionario = new HashSet<AsignacionCuestionario>();
        }
    
        public int IDAlumno { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string NumIdentificacion { get; set; }
        public int IDCat_TipoDocumento { get; set; }
        public int IDAlumnoGrupo { get; set; }
    
        public virtual AlumnosGrupos AlumnosGrupos { get; set; }
        public virtual Cat_TipoDocumento Cat_TipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionCuestionario> AsignacionCuestionario { get; set; }
    }
}
