//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCuestionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsignacionCuestionario()
        {
            this.RespuestasAlumnosCuestionarios = new HashSet<RespuestasAlumnosCuestionarios>();
        }
    
        public int IDAsignacionCuestionario { get; set; }
        public Nullable<int> IdCuestionario { get; set; }
        public Nullable<int> IDAlumno { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> NotaTotal { get; set; }
        public int IDUsuario { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Cuestionarios Cuestionarios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestasAlumnosCuestionarios> RespuestasAlumnosCuestionarios { get; set; }
    }
}
