//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCuestionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsignacionCuestionario()
        {
            this.RespuestasAlumnosCuestionarios = new HashSet<RespuestasAlumnosCuestionarios>();
        }
    
        public int IDAsignacionCuestionario { get; set; }
        public Nullable<int> IdCuestionario { get; set; }
        public Nullable<int> IDAlumno { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> NotaTotal { get; set; }
        public int IDUsuario { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Cuestionarios Cuestionarios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestasAlumnosCuestionarios> RespuestasAlumnosCuestionarios { get; set; }
    }
}
