//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuestionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuestionarios()
        {
            this.AsignacionCuestionario = new HashSet<AsignacionCuestionario>();
            this.Preguntas = new HashSet<Preguntas>();
        }
    
        public int IdCuestionario { get; set; }
        public int IdInstrucciones { get; set; }
        public string IndicadoresEvaluacion { get; set; }
        public string Nivel { get; set; }
        public string Curso { get; set; }
        public string Area { get; set; }
        public Nullable<decimal> PorcentajeAprendizaje { get; set; }
        public int IDQuimestre { get; set; }
        public int IDUsuario { get; set; }
        public int IDMateria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionCuestionario> AsignacionCuestionario { get; set; }
        public virtual Instrucciones Instrucciones { get; set; }
        public virtual Materias Materias { get; set; }
        public virtual Quimestre Quimestre { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preguntas> Preguntas { get; set; }
    }
}
