//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuestionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuestionarios()
        {
            this.AsignacionCuestionario = new HashSet<AsignacionCuestionario>();
            this.Preguntas = new HashSet<Preguntas>();
        }
    
        public int IdCuestionario { get; set; }
        public int IdInstrucciones { get; set; }
        public string IndicadoresEvaluacion { get; set; }
        public string Nivel { get; set; }
        public string Curso { get; set; }
        public string Area { get; set; }
        public Nullable<decimal> PorcentajeAprendizaje { get; set; }
        public int IDQuimestre { get; set; }
        public int IDUsuario { get; set; }
        public int IDMateria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionCuestionario> AsignacionCuestionario { get; set; }
        public virtual Instrucciones Instrucciones { get; set; }
        public virtual Materias Materias { get; set; }
        public virtual Quimestre Quimestre { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preguntas> Preguntas { get; set; }
    }
}
