//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preguntas()
        {
            this.Respuestas = new HashSet<Respuestas>();
        }
    
        public int IDPregunta { get; set; }
        public string Pregunta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> puntaje { get; set; }
        public int IdCuestionario { get; set; }
    
        public virtual Cuestionarios Cuestionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuestas> Respuestas { get; set; }
    }
}
