//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestasAlumnosCuestionarios
    {
        public int IDRespuestasAlumnosCuestionarios { get; set; }
        public Nullable<int> IDRespuesta { get; set; }
        public string TextoRespuesta { get; set; }
        public int IDAsignacionCuestionario { get; set; }
    
        public virtual AsignacionCuestionario AsignacionCuestionario { get; set; }
        public virtual Respuestas Respuestas { get; set; }
    }
}
