//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respuestas()
        {
            this.RespuestasAlumnosCuestionarios = new HashSet<RespuestasAlumnosCuestionarios>();
        }
    
        public int IDRespuesta { get; set; }
        public Nullable<int> IDPregunta { get; set; }
        public string Respuesta { get; set; }
        public Nullable<bool> EsCorrecta { get; set; }
    
        public virtual Preguntas Preguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestasAlumnosCuestionarios> RespuestasAlumnosCuestionarios { get; set; }
    }
}
