//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestasAlumnosCuestionarios
    {
        public int IDRespuestasAlumnosCuestionarios { get; set; }
        public Nullable<int> IDRespuesta { get; set; }
        public string TextoRespuesta { get; set; }
        public int IDAsignacionCuestionario { get; set; }
    
        public virtual AsignacionCuestionario AsignacionCuestionario { get; set; }
        public virtual Respuestas Respuestas { get; set; }
    }
}
